### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by achinverma** [evgenyneu/aes-crypto-android#1]
hi i am using your library for decryption of my web service response in android i am using this method  ,
But i am not able to run this method in AsyncTasks doInBackground method it gives me error can create handler inside thread, how can i run this  method in doInBackground  ?
try {
                            //Utils.showProgressDialog(context);
                            JsEncryptor mJsEncryptor;
                            mJsEncryptor = JsEncryptor.evaluateAllScripts((Activity) context);
                            mJsEncryptor.decrypt(result,  Constants.Key,new JsCallback() {
                                @Override
                                public void onResult(String decryptedTextFromJs) {
                                    //System.out.println("output decryptedTextFromJs is----"+decryptedTextFromJs);
                                    result = decryptedTextFromJs;
                                    parse_login_response(result);
                                }
                            });
                        } catch (Exception e) {
                            System.out.println("Exception -decryptData-"+e.toString());
                        }

**Comment by evgenyneu** [comment]
Hi, sorry for late response. I am using the [js evaluator library](https://github.com/evgenyneu/js-evaluator-for-android). It creates an invisible web view and evaluates JavaScript in it. I think web view is supposed to be operated in UI thread only.

**Comment by Aman91Goyal** [comment]
Hi, I am also using same library for encryption and decryption in node and android side .

its working fine in node side for decryption any amount of data(in terms of size) but when i am applying decryption  on same string in android side, its not working .
so can you please tell me is there any limit on data for decryption . But i don't think so because some times it works some times its not returning any data.

Its working fine for small data.

```
        mJsEncryptor.decrypt(encryptedData, "xxxxx",
                new JsCallback() {
            @Override
            public void onResult(final String decryptedTextFromJs) {
```

log.e("Output --",decryptedTextFromJs);
                    Intent intent = new Intent("com.testing");
                    intent.putExtra("data", decryptedTextFromJs);
                    mcontext.sendBroadcast(intent);
                }

```
        }
        );
```

There is no output in Output --
Looking forward for your response.

**Comment by evgenyneu** [comment]
Hi, interesting. If you could send me the problematic text string and
password, I will try to debug it. Also, the Android version number. Thanks.

**Comment by Aman91Goyal** [comment]
Hi, Please share your email id .

**Comment by evgenyneu** [comment]
sausageskin   At gmail    com
