### ISSUE TITLE
not wowrking with proguard

### ISSUE THREAD

**Issue by achinverma** [evgenyneu/aes-crypto-android#2]
hi , i am using this library to encrypt strings in my code , but when i enable pro-guard it is not encrypting the strings and if i disable the pro-guard then it is working fine, please guide me ?

**Comment by evgenyneu** [comment]
Hi, I have never used pro-guard myself. Can you give more information so I can look into it?

1) By "this library" do you mean https://github.com/evgenyneu/js-evaluator-for-android? Because this repository is not a library - it is an app.
2) How do you turn pro-guard on?

**Comment by achinverma** [comment]
i am using eclipse and 
in your project directory find project.properties file. You should have similar line:

proguard.config=${sdk.dir}/tools/proguard/proguard-android.txt:proguard-project.txt:proguard-google-api-client.txt
just uncomment this line, now your proguard is enable 
http://stackoverflow.com/questions/20142247/proguard-enabling-in-eclipse

**Comment by evgenyneu** [comment]
No idea, sorry I can not help you with this - never used pro-guard.

**Comment by achinverma** [comment]
ok, do you  know any other aes-crypto- Library ,which is compatible with android and node ?

**Comment by evgenyneu** [comment]
No sorry I am not aware of any similar JavaScript based libraries for
Android.
